name: 'Archway Build and Test'
on:
  push:
    branches:
  pull_request:
env:
  POSTGRES_HOST: localhost
  SBT_OPTS: '-Xss64m'
jobs:
  build:
    name: 'Build and test'
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: archway
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '9'
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: npm install typescript
      - run: npm install
      - run: npm test
      - run: ./flyway/flyway migrate -url="jdbc:postgresql://localhost:5432/archway" -user=postgres -password=postgres
      - run: sbt common/test
      - run: sbt api/test
      - run: sbt provisioning/test
      - run: sbt "set every test in assembly := {}" integration-test/assembly
      - run: sbt integration-test/test:package
      - run: sbt common/test:package
